spring.application.name=eco-web-api

spring.datasource.url=${DB_URL:jdbc:mysql://127.0.0.1:3306/ecommerce?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:qqappzWzj.}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

alipay.gateway-url=https://openapi.alipay.com/gateway.do
alipay.notify-sign=${ALIPAY_NOTIFY_SIGN:demo-sign}
alipay.public-key=${ALIPAY_PUBLIC_KEY:}
alipay.charset=${ALIPAY_CHARSET:utf-8}
alipay.sign-type=${ALIPAY_SIGN_TYPE:RSA2}
