spring.application.name=eco-web-api

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/ecommerce?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=qqappzWzj.

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

alipay.gateway-url=https://openapi.alipay.com/gateway.do
alipay.notify-sign=demo-sign